Hosts:
  - Host:
    IP: 192.1.1.1
    Type: cisco-ios-xr
    SnmpConfig:
      Version: 3
      Port: 161
      Timeout: 6
      Retries: 1
      Community: mycommunity
    Features:
      Uptime: true
      InterfaceCounters: true
  - Host:
    IP: 192.1.1.2
    Type: cisco-ios
    SnmpConfig:
      Version: 2
      Port: 161
      Timeout: 6
      Retries: 1
      Community: mycommunity
    Features:
      Uptime: true
      InterfaceCounters: true